# Generated by Django 4.0.1 on 2022-01-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pesanan_waktu_pemesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='total_pesanan',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='total_pesanan_akhir',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
