# Generated by Django 4.0.1 on 2022-01-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pesanan_id_kode_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_pesanan',
            name='id_pesanan',
            field=models.IntegerField(default=None),
        ),
    ]
