# Generated by Django 4.0.1 on 2022-01-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pesanan_total_pesanan_akhir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjual',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
