# Generated by Django 4.0.1 on 2022-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_image_alter_product_penjual_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kode_promo',
            name='deskripsi',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kode_promo',
            name='kode_promo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kode_promo',
            name='persentase_diskon',
            field=models.IntegerField(),
        ),
    ]
