# Generated by Django 4.0.1 on 2022-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_kode_promo_deskripsi_alter_kode_promo_kode_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kode_promo',
            name='kode_promo',
            field=models.CharField(max_length=50),
        ),
    ]
