# Generated by Django 4.0.1 on 2022-01-18 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_detail_pesanan_created_at_kode_promo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('pembeli_id', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detail_pesanan',
            name='id_pesanan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail_pesanan',
            name='id_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail_pesanan',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='pembeli_id',
            field=models.IntegerField(),
        ),
    ]
